apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-model
  labels:
    app: chess-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chess-model
  template:
    metadata:
      labels:
        app: chess-model
    spec:
      containers:
        - name: chess-model
          image: ethancruz/chess_model:v1.0.18
          env:
          - name: mongo_url
            value: "mongodb://mongodb-service:27017/your-db-name"
#           ports:
#           - containerPort: 5000

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: chess-model-service
# spec:
#   selector:
#     app: chess-model
#   ports:
#   - protocol: TCP
#     port: 5000
#     targetPort: 5000
#   type: LoadBalancer
