---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-engine
  labels:
    app: chess-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chess-engine
  template:
    metadata:
      labels:
        app: chess-engine
    spec:
      containers:
      - name: pytorch-container
        # Replace with your actual Docker image
        image: ethancruz/chess_model:v1.0.21
        # Expose ports 8888 (commonly Jupyter) and 5000 (commonly Flask)
        ports:
        - containerPort: 8888
        - containerPort: 5000
        # Resource requests and limits:
        resources:
          requests:
            memory: "6Gi"
            cpu: "3"
          limits:
            memory: "6Gi"
            cpu: "3"

---
apiVersion: v1
kind: Service
metadata:
  name: pytorch-service
spec:
  selector:
    app: chess-engine
  type: NodePort
  ports:
    - name: jupyter
      port: 8888       # Service port
      targetPort: 8888 # Container port in the Deployment
      protocol: TCP
      nodePort: 30088   # Optional; if omitted, K8s will assign a random NodePort
    - name: tensroboard
      port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 30050    # Optional; if omitted, K8s will assign a random NodePort
